[build]
# Default to x86 for QEMU testing if not specified
target = "x86_64-unknown-none" 

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.x86_64-unknown-none]
runner = "bootimage runner"


[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]
